### ISSUE TITLE
Create Mapshader Services Directory Bokeh Server App

### ISSUE THREAD

**Issue by brendancol** [makepath/mapshader#57]
- [ ] create new bokeh server app which lists all mapshader services
- [ ] allows for previewing each service
- [ ] shows server usage stats / diagnostics (psutil)

**Comment by IuryPiva** [comment]
You mean something like [flask_embed.py](https://github.com/bokeh/bokeh/blob/2.3.1rc2/examples/howto/server_embed/flask_embed.py)? how is it better than the way we do at present?
