### ISSUE TITLE
README instructions for user-specified YAML config incorrect

### ISSUE THREAD

**Issue by ianthomas23** [makepath/mapshader#94]
If I follow the instructions for user-specified YAML config from the README, i.e. create the suggested `my_services.yaml` and then run
```
python mapshader/flask_app.py -f my_services.yaml
```
I get
```
File "/home/iant/github/mapshader/mapshader/services.py", line 242, in parse_sources
    for service_type in source['service_types']:
KeyError: 'service_types'
```
If I add the following to `my_services.yaml` (I am guessing here)
```
sources:
  - name: Elevation
    <existing lines>
    service_types:
      - tile
```
then I get passed the previous error but see
```
AssertionError: View function mapping is overwriting an existing endpoint function: Elevation tile
```
This occurs with both master and the 0.0.9 release.

So there is some inconsistency between the code and the README.

**Comment by giancastro** [comment]
Hey @ianthomas23! I created a PR (#95) to fix the YAML config example. Could you try to use the new one?

**Comment by ianthomas23** [comment]
@giancastro Yes, that works perfectly for me. Thanks very much!
